### ISSUE TITLE
performance ใน Form::render()

### ISSUE THREAD

**Issue by phpinfo-in-th** [goragod/kotchasan#1]
`Form::render()` มีหลายจุดที่ทำให้ performance ลดลงโดยไม่จำเป็น และสร้าง html ที่ไม่ well formed
โดยเฉพาะในจุดที่วนลูปเพื่อสร้าง attributes

```php
foreach ($this->attributes as $k => $v) {
	if (is_int($k)) {
		if (!empty($v)) {
			$prop[$v] = $v;
		}
	} elseif (in_array($k, array('checked', 'readonly'))) {
		if ($v) {
			$prop[$k] = $k;
		}
	} elseif (in_array($k, array('result'))) {
		$prop[$k] = 'data-'.$k.'="'.$v.'"';
	} elseif (preg_match('/^on([a-z]+)/', $k, $match)) {
		$event[$match[1]] = $v;
	} else {
		if (!in_array($k, array('itemClass', 'labelClass', 'label', 'comment', 'value', 'dataPreview', 'previewSrc', 'options', 'optgroup', 'validator'))) {
			if (is_int($v) || is_bool($v)) {
				$prop[$k] = $k.'='.$v;
			} else {
				$prop[$k] = $k.'="'.$v.'"';
			}
		}
		$$k = $v;
	}
}

```
จะเห็นว่า
* ใช้ string concatenation
* ใช้ `in_array()` ใน loop และทดสอบกับ array ที่สร้างใหม่ทุกครั้ง ซึ่งใน worst case นั้น จะมีการเรียกใช้ in_array() และมีการสร้าง array เพื่อใช้ในการทดสอบ 3 ครั้ง ใน 1 รอบ foreach
* มีการพยายามตรวจสอบ $v ว่าเป็น int หรือ bool หรือไม่ด้วย `is_int()` และ `is_bool()` ซึ่งใน worst case จะทำให้ 1 รอบ foreach มีการเรียกใช้ function ทั้งหมด 7 ครั้ง และสร้าง array 3 ครั้ง เพียงเพื่อสร้าง html attribute 1 ตัว
* มีการพยายามตรวจสอบ $v ว่าเป็น int หรือ bool และทำเพียงเพื่อตัดสินใจว่าจะใส่ `"` หรือไม่ใส่ ซึ่งไม่จำเป็นเลย และทำให้ html attribute นั้นไม่ถูกต้องตามหลัก XML หรือ XHTML ดังนั้นควรใช้ " ครอบ attribute ทั้งหมด
* ไม่ปลอดภัยจาก XSS เพราะไม่มีการ escape ค่าของ attribute ด้วย `htmlspecialchars()` เลย

วิธีแก้
* เปลี่ยน string concatenation เป็น string interpolation
* ใช้ `switch` แทน `in_array()`
* ไม่ต้องตรวจสอบค่าของ $v ด้วย `is_int()` และ `is_bool()`
* ครอบค่าของ attribute ด้วย `"` และใช้ `htmlspecialchars()` เพื่อ escape ค่าของ attribute

```php
foreach ($this->attributes as $k => $v) {
	if (is_int($k)) {
		if (!empty($v)) {
			$prop[$v] = $v;
		}
		continue;
	}
	switch ($k) {
		case 'checked':
		case 'readonly':
			$prop[$k] = $k;
			continue 2;
		case 'result':
			$v = htmlspecialchars($v);
			$prop[$k] = "data-{$k}=\"{$v}\"";
			continue 2;
		case 'itemClass':
		case 'labelClass':
		case 'label':
		case 'comment':
		case 'value':
		case 'dataPreview':
		case 'previewSrc':
		case 'options':
		case 'optgroup':
		case 'validator':
			break;
		default:
			if (preg_match('/^on([a-z]+)/', $k, $match)) {
				$event[$match[1]] = $v;
				continue 2;
			}
			$v = htmlspecialchars($v);
			$prop[$k] = "{$k}=\"{$v}\"";
			break;
	}
	$$k = $v;
}
```

**Comment by goragod** [comment]
เยี่ยมไปเลย ขอบคุณครับ

เมื่อวานที่คุยกันมีแก้ไขไปอันนึงตือ 
route_rules ผมเอาไปใส่ไว้ใน  Router 
แล้ว 
แต่ก็ยังไม่ค่อยแน่ใจเท่าไรนัก 
ว่าหากต้องการจะแก้ไข rules 
จะต้องทำแบบไหน

**Comment by phpinfo-in-th** [comment]
เห็นแล้วครับ แต่จริงๆ ควร initialize ตรงจุดที่ประกาศ $router_rules เลยครับ เพราะถ้า ผู้ใช้ extends Router มันจะไม่ถูกเขียนทับตอน _construct() ครับ

**Comment by goragod** [comment]
เห็นด้วยกับ switch case 
แต่สงสัยว่าทำไมใช้ continue 2 
มันต่างจาก break ยังไง 
เห็นในคู่มือมันบอกว่าเหมือนกัน

**Comment by phpinfo-in-th** [comment]
continue 2; คือ continue foreach ครับ ไม่ใช่ break switch
