### ISSUE TITLE
การเข้ารหัสของพาสเวิร์ดนั้นเราควรใช้พวก hash (1 way encryption)

### ISSUE THREAD

**Issue by pjamenaja** [goragod/kotchasan#2]
ผมได้ทำการรีวีวในเรื่องของ security บางส่วนพบว่าน่าจะมีช่องโหว่บางอย่างนะครับ เช่น

1. การเข้ารหัสพาสเวิร์ดไม่ควรที่จะ encrypt, decrypt กลับไปกลับมาได้ เราควรใช้ hash algorithm ที่มีอยู่แล้วใน php มาใช้ให้เป็นประโยชน์นะครับ

2. ไม่ควรมีการส่งพาสเวิร์ด กลับไปที่ cookie ถึงแม้ว่าจะทำการ encrypt แล้วก็ตาม ส่งที่ส่งกลับไปให้กับ client ควรจะเป็นอย่างเดียวเท่านั้นคือ session แล้วเก็บข้อมูลที่เกี่ยวกับ session นั้นไว้ใน server side จะปลอดภัยกว่าครับ

3. ไม่ควรที่จะเขียน function สำหรับการ encode, decode เอาเอง ควรที่จะใช้ที่มีอยู่แล้วเพราะค่อนข้างจะสตรองกว่าและถูกพิสูจน์กันมาแล้ว

**Comment by webdevxp** [comment]
ไม่มีเสียงตอบรับจากหมายเลขที่ท่านเรียก 555

**Comment by goragod** [comment]
สามารถ commit code มาได้ครับ ถ้าสามารถทำงานได้ตามวัตถุประสงค์ของคลาส และ ดีกว่าจริง และ ทำงานร่วมกันส่วนอื่นๆได้ ถึงจะได้รับการพิจารณาครับ ถ้าขาดข้อใดข้อหนึ่ง ไม่ผ่านครับ

**Comment by webdevxp** [comment]
คงไม่มีใคร commit มาแล้วมั้งครับถ้าเห็นแบบนี้

**Comment by pjamenaja** [comment]
ไว้รอให้คนที่เค้าสนใจเอางานของคุณ กรกฎ ไปใช้งานต่อให้เค้าช่วยมาปรับแก้ให้นะครับเรื่องเกี่ยวกับ security คือผมลองไล่ดูโค้ดคุณแล้ว มันโยงใยพันกันมั่วไปหมดเกินกว่าที่จะแก้ได้ในเวลาอันสั้นนะครับ แต่โดยหลักการแล้วโค้ดมีปัญหาเรื่อง security แน่นอนครับตามที่ได้เรียนแจ้งไปนะครับ ผมอยากจะแนะนำว่า

1. เราควรแจ้งเรื่องนี้ให้กับคนที่จะนำเฟรมเวิร์ไปใช้ ให้เค้าตัดสินใจพิจารณาเองนะครับ
2. คุณควรจะแก้เรื่องเหล่านี้อย่างเร่งด่วน เพราะว่ามีลูกค้าหลายเจ้าที่เอาไปใช้แล้วแน่นอน แล้วถ้าเจอ hack ขึ้นมาจริง ๆ มันจะไม่คุ้มกันนะครับ
3. เปิด issue เอาไว้เพื่อให้คนที่พร้อมที่จะช่วยแก้เข้ามาแก้ไขต่อไปนะครับ กรุณาอย่าลบความเห็นของผมเลยนะครับ เป็นการให้ข้อเสนอแนะอย่างกัลยาณมิตร ไม่ได้มีเจตนาอื่นแอบแฝงเลย

ขอบคุณครับ

**Comment by webdevxp** [comment]
ทำไมต้องลบความเห็นกันด้วยล่ะครับ ผมใช้คำไม่สุภาพ หยาบคาย หรืออะไรยังไงครับ

**Comment by webdevxp** [comment]
ของผมนี่อาจจะมองได้ว่าเป็นการแซะ ผมยอมรับ แต่ความเห็นของคุณ @pjamenaja นี่ผมมองว่าไม่ได้มีเจตนาอะไรเลยนะครับ แล้ว issue นี้เนี่ย คุณ close โดยที่ไม่มีการตอบกลับอะไรคุณ @pjamenaja เลย ไม่คิดว่ามันเกินไปหน่อยเหรอครับ ทั้งๆ ที่เขามาแนะนำดีๆ ผมก็เห็นคุณกรกฏพูดบ่อยๆ นี่ครับ ว่าอยากได้ความเห็นหรือคนมาช่วย แต่พอได้ความเห็นมีคนมาช่วยจริงๆ ทำไมทำแบบนี้ล่ะครับ
