### ISSUE TITLE
class Password

### ISSUE THREAD

**Issue by phpinfo-in-th** [goragod/kotchasan#2]
class Password ใช้ algo อย่างง่ายเพื่อ encode และ decode รหัสผ่าน
ซึ่งถึือว่าไม่เหมาะสมอย่างยิ่ง ควรเปลี่ยนไปใช้ cryptographic function เช่น `openssl` หรือ `mcrypt` แทน

และยังมี bug ทั้งใน `encode()` และ `decode()` เพราะว่าใช้ `mb_strlen()` ในการหาความยาวของสตริง แต่เวลาอ่านสตริง ใช้ `substr()` และ `ord()` ที่ไม่ได้เป็น multibyte safe
วิธีแก้คือ ใช้ `strlen()`

```php
public static function encode($string)
{
	$key = sha1((string)\Kotchasan::$config->password_key);
	//$str_len = mb_strlen($string);
	//$key_len = mb_strlen($key);
	$str_len = strlen($string);
	$key_len = strlen($key);
	$j = 0;
	$hash = '';
	for ($i = 0; $i < $str_len; $i++) {
		$ordStr = ord(substr($string, $i, 1));
		$j = $j == $key_len ? 0 : $j;
		$ordKey = ord(substr($key, $j, 1));
		$j++;
		$hash .= strrev(base_convert(dechex($ordStr + $ordKey), 16, 36));
	}
	return $hash;
}
```

**Comment by goragod** [comment]
ขอความคิดเห็นเธอหน่อย

https://github.com/goragod/test/blob/master/core/password.php คลาส Password ตามนี้

ในความคิดเห็นของเธอ ถ้าเธอต้องโหลด key จากไฟล์นี้  https://github.com/goragod/test/blob/master/settings/config.php เธอจะมีแนวทางการเขียนอย่างไร

**Comment by phpinfo-in-th** [comment]
คือถ้าเป็นผม มันจะไม่เหมือนกันเลยตั้งแต่แนวคิดแล้วครับ เพราะผมจะเลี่ยง singleton เลี่ยง static method
อะไรก็ตามที่มี config ผมก็จะทำให้มันเป็น class แบบต้องการ instance
ถ้าให้ยกตัวอย่าง คือพี่มอง class Password เป็นที่รวมฟังก์ชั่น
แต่ผมจะมอง class Password เป็น Object เวลาจะใช้ต้องมี instance และ ณ จุดที่สร้างก็ส่งผ่าน password_key ไปเป็น config ให้มัน
แต่ไม่ได้หมายความว่าการใช้ helper pattern (class รวม static method) ไม่ดีนะครับ
แต่ในกรณีนี้ class Password สามารถ config ได้ มันควรจะเป็น instance
อย่างที่เคยแนะนำไปครับ ให้ลองศึกษาเรื่อง DI Container ดู มันจะแก้ปัญหาพวกนี้ได้

**Comment by goragod** [comment]
ไม่ต้องสนใจแนวคิดผมสิ เอาแนวคิดเธอล้วนๆ ถ้ามันแก้ปัญหาที่ผมเจอได้ ผมก็พร้อมจะปรับแนวคิด

ตอนนี้ ปัญหาที่น่าจะเจอก็คือ ไม่ว่ายังไงก็ตาม เราก็ยังคงต้องพึ่งพา Libraly ภายนอกอยู่ ยกตัวอย่างเช่น Class ที่เป็นคำถาม ถ้าเราไม่ include เอา config เข้ามา เราจะเอาค่า $key มาใช้ได้ไง (ผมใช้ตัวอย่างนี้เพราะมันมีตัวแปรภายนอกแค่ตัวเดียว ทำให้ง่ายต่อการทำความเข้าใจ)

ในกรณีของ DI มันก็ต้องมีการ เรียกใช้ class จากภายนอกอยู่ดี  (เพื่อเอา config เข้ามา) การแก้ไขค่าของ config ภายในโค้ดโดยตรงไม่น่าเป็นเรื่องดีแน่

**Comment by goragod** [comment]
เพิ่มเติมนะ ความหมายของ singleton ของเธอคือ ให้เลี่ยงแบบนี้
echo \Password::decode(\Password::encode('ทดสอบการเข้ารหัส และ การถอดรหัส'));

และ ให้ใช้แบบนี้แทน ใช่มั้ย
$pw = new \Password();
$pw->setKey('1234');
echo $pw->decode($pw->encode('ทดสอบการเข้ารหัส และ การถอดรหัส'));

**Comment by phpinfo-in-th** [comment]
จากคอมเม้นท์#3 ผมว่าพี่ยังเข้าใจ DI ผิดอยู่ หรือไม่ก็ยังไม่เข้าใจว่าจะเอามันมาใช้ยังไง
และสาเหตุที่ทำให้พี่ไม่เข้าใจ DI ก็เป็นเพราะพี่ไม่เคยใช้ interface ซึ่งที่เคยคุยกันพี่บอกว่าเคยใช้ แต่ไม่เห็นประโยชน์ของมัน เลยเลิกใช้
และถ้าพี่ไม่เห็นประโยชน์ของมัน แสดงว่าพี่ยังเข้าใจ OOP พื้นฐานไม่ครบ ซึ่งเรื่อง DI เนี่ย มันคือการประยุกต์ใช้ OOP แบบเต็มๆ เลย ถ้าไม่เข้าใจ OOP ก็ไปต่อลำบากครับ
ยังไงลองศึกษาใหม่ดูอีกทีครับ
