### ISSUE TITLE
ประโยชน์ และ performance ของ class Input

### ISSUE THREAD

**Issue by phpinfo-in-th** [goragod/kotchasan#3]
Kotchasan มี class Input ที่มี Helper method หลายตัวที่พยายามจะแปลงค่า input ให้เป็น PHP value
เช่น `Input::get()` หรือ `Input::filter()`
และบาง method มีการ filter input ตามชื่อของค่าที่ส่งมา เช่น `$_POST['topic']` ก็จะถูก filter ด้วย `String::topic()`
นั่นหมายความว่าฟังก์ชั่นเหล่านี้จะเปลี่ยนแปลงข้อมูลโดยไม่สนว่ามันจะจำเป็นหรือไม่
และตีกรอบการใช้งานของผู้ใช้มากจนเกินไป เพราะไม่สามารถเลือกชื่อตัวแปรที่จะใช้ได้เอง
แม้จะเรียกว่า Framework (กรอบการทำงาน) แต่ก็ไม่ควรจะตีกรอบทุกอย่างมากขนาดนี้ แม้แต่ CMS Framework อย่าง Wordpress หรือ Drupal ก็ไม่ได้ทำงานในลักษณะนี้

แถมแลกมาด้วย performance เพราะฟังก์ชั่นเหล่านี้มีการใช้ฟังก์ชั่นที่ตรวจชนิดของตัวแปรเช่น `is_int()` และใช้ `preg_match()` ในการตรวจสอบชื่อ ซึ่งอาจจะเป็นเป้าหมายของการโจมตีแบบ DDOS ได้ เช่นผู้ใช้ส่งข้อมูล POST มา 1000 ตัว Kotchansan ก็ต้องวนรอบ preg_match() 1000 ครั้งแล้ว เพียงแค่ตรวจว่าชื่อ input นั้นอยู่ในกลุ่มที่ต้องแปลงค่าหรือไม่

**Comment by goragod** [comment]
Input::get() ทำหน้าที่อ่านค่าจากตัวแปร เพื่อป้องกัน warning กรณีที่ไม่พบตัวแปร เช่น checkbox ที่ไม่ได้ติ๊กถูก และ แปลงค่า ตามค่า default คล้าย filter_input() ของ PHP
Input::filter() ทำหน้าที่รับค่าจากการ $_POST หรือ $_GET ทั้งหมด ในคราวเดียว และส่งออกเอาท์พุตเป็น array ประโยชน์ของฟังก์ชั่นนี้ ใข้ในการรับค่าจากฟอร์ม โดยตรง และ ฟอร์มอาจเกิดจาก คลาสสำหรับสร้างฟอร์ม จำเป็นต้องมีรูปแบบที่ชัดเจน
ผู้ใช้สามารถเลือกวิธีการรับค่าได้ด้วยตัวเอง ด้วยวิธีใดก็ได้ตามที่ต้องการ เพราะระบบไม่ได้บังคับว่าจะต้องรับค่าด้วยวิธีใด
ในกรณีที่ต้องการเลี่ยงการแปลง Input สามารถทำได้โดยการไม่ระบุ $default ลงไป ก็จะไม่ผ่านการตัวจสอบใดๆแล้ว (ตรวจสอบแค่มีตัวแปรส่งมาหรือไม่)

**Comment by phpinfo-in-th** [comment]
ผมทราบครับ ว่าใช้ทำอะไร แต่ประเด็นของผมคือ มันเป็น Helper ที่มีลักษณะ domain specific คือเจาะจงเกินไป และทำงานมากเกินไป (เช่นแปลง string ให้เป็น PHP value)
ความหมายของ domain specific คืออย่างเช่น key 'text' จะถูก escape ด้วย `String::htmlspecialchars()` ซึ่งจริงๆ `htmlspecialchars()` ควรจะใช้สำหรับ output เท่านั้น
ดังนั้นประโยชน์ของมันจะลดลง เพราะไม่สามารถใช้เพื่อการอื่น นอกจากอนุมานเอาว่าข้อมูลที่ผ่านการ filter จะต้องเอาไปใช้ตามที่คุณกำหนดไว้เท่านั้น มันจะเป็นปัญหาเมื่อผู้ใช้ต้องการสร้างระบบที่แตกต่างหรือใหญ่ขึ้น
และไม่ใช่แค่ class นี้ เกือบทุก class ของ Kotchasan มีลักษณะเหมือนกันหมด
ผมเข้าใจครับว่าคุณมีแนวคิดอย่างไร ต้องการอะไร แต่ไม่มี Framework ไหนเขาทำแบบนี้ครับ เพราะมันจะทำให้มันไม่ใช่ Framework แต่จะเป็นแค่ domain specific library
