### ISSUE TITLE
LoginInterface

### ISSUE THREAD

**Issue by webdevxp** [goragod/kotchasan#3]
`LoginInterface` ปรากฏอยู่แค่ใน 2 ไฟล์ คือ `Kotchasan/Interfaces/Loginterface` ซึ่งเป็นไฟล์ของมันเอง กับ `Kotchasan/Login.php` จึงทำให้ interface นี้ไม่มีประโยชน์อะไรเลย และทำให้ระบบต้องเสียเวลาโหลดไฟล์เพิ่มอีก 1 ไฟล์ ถ้าไม่ได้ตั้งใจว่าในอนาคตจะให้ interface ทำอะไรที่มีประโยชน์จริงๆ แนะนำว่าควรตัดทิ้งไปเลยครับ

**Comment by goragod** [comment]
มีครับ มันสามารถนำไปใช้ได้ในกรณ๊ที่ต้องการแก้ไขกระบวนการ login ด้วยตัวเอง

**Comment by webdevxp** [comment]
ยังไงเหรอครับ เพราะไม่เห็นว่ามันใช้ในจุดอื่นๆ ของเฟรมเวิร์คเลย

**Comment by goragod** [comment]
มันสามารถนำไปใช้นอก framework ได้ครับ เช่นใช้ใน project ถ้าจะบอกให้ลบ interface จริงๆ มีอีกหลายตัว ที่ไม่เคยถูกเรียกใช้เลยครับ แต่ที่ต้องมีบางครั้งก็เพื่อกันคนถาม (ว่ามีไอ้นั่นมั้ย ไอ้นี่มั้ย ประมาณนี้) บางครั้ง ก็ต้องใส่ไว้เพื่อความสามารถอื่นๆครับ ซึ่งมีได้หลายกรณี กรณีที่สำคัญที่สุดคือ class ที่ถูกออกมา เพื่อการ override ครับ เช่น class Login นี่แหละ

หมายเหตุ ตอนออกแบบทีแรกผมก็คิดแบบนี้แหละ ว่าจะทำไปทำไม เขียนมันใช้โต้งๆ เลยก้ได้ แต่พอทำเข้าจริงๆ มันมีประโยชน์ครับ หลายๆคลาสผมยังอยกปรับใหม่ใช่ interface ก่อนเลย

**Comment by webdevxp** [comment]
ถ้าเรื่อง override class นี่ผมเข้าใจครับ มันปกติอยู่แล้ว แต่ interface `LoginInterface` ผมไม่เข้าใจจริงๆ ครับว่ามันจะใช้ยังไง เพราะถ้าจะ override class `Login` มันไม่จำเป็นเลยที่จะต้องมี `LoginInterface`
อย่างเฟรมเวิร์คอื่นๆ ทุก interface ที่อยู่ใน project เดียวกันมันจะมีที่ใช้ในตัว project นั้นๆ หมดครับ เพราะ interface มันตรงตัวอยู่แล้วว่าคือ interface ถ้าทำไว้มันต้องมีการบังคับใช้ในสักจุดของโค้ด

**Comment by goragod** [comment]
ออ ครับ
