### ISSUE TITLE
YouTube API Key exposed

### ISSUE THREAD

**Issue by Maikuolan** [goragod/kotchasan#4]
*See [projects/youtube/modules/index/views/index.php](https://github.com/goragod/kotchasan/blob/master/projects/youtube/modules/index/views/index.php).*

**Comment by goragod** [comment]
thank

**Comment by DanielRuf** [comment]
Well, the projects should be decoupled as additional repository imho. Not very secure examples like https://github.com/goragod/kotchasan/blob/master/projects/admin/settings/config.php (no password_hash or bcrypt used, can be used with password_compat). Just my two cents on this.
