### ISSUE TITLE
ถ้าหาก user ส่งสตริงที่มีตัวอักขระพิเศษเข้ามาเช่น ' (single quote) จะมีปัญหามั้ยครับ

### ISSUE THREAD

**Issue by pjamenaja** [goragod/kotchasan#4]
ถ้าหาก user ส่งสตริงที่มีตัวอักขระพิเศษเข้ามาเช่น ' (single quote) จะมีปัญหามั้ยครับ คือ ผมลอง ๆ ดูโค้ดคร่าว ๆ แล้วเหมือนกับว่าเฟรมเวิร์คจะไม่ได้ใช้วิธีการ bind ตัวแปรตอน execute sql แล้วก็ไม่มีการทำการ escape character อย่างเช่นพวก single quote

ถ้าหากว่ามีการรองรับตรงนี้แล้วก็ต้องขออภัยด้วยครับ

**Comment by goragod** [comment]
https://doc.kotchasan.com/class-Kotchasan.InputItem.html
