### ISSUE TITLE
การสนับสนุน composer?

### ISSUE THREAD

**Issue by phpinfo-in-th** [goragod/kotchasan#4]
Framework และ Library PHP ทั่วไปจะสนับสนุน composer เพราะเป็นมาตรฐานไปแล้ว
บางตัวก็บังคับใช้ composer หรือไม่ก็สามารถใช้แบบ standalone ได้ ด้วย autoload ไฟล์ที่กำหนดไว้
ไม่ทราบว่า Kotchasan มีแผนที่จะสนับสนุน composer หรือไม่ครับ

**Comment by goragod** [comment]
ส่วนตัว ไม่ชอบ composer เท่าไร และเห็นปัญหาของการใช้ composer หลายอย่าง (โดยเฉพาะกับผู้ใช้ระดับ end user)
เจตนารมณ์ในการออกแบบ Kotchasan แต่แรกก็ไม่ได้สนับสนุน composer (ตั้งใจ)
แต่ในอนาคตยังไม่แน่ครับ
