### ISSUE TITLE
การเข้ารหัส password ด้วย algorithm ที่ไม่ปลอดภัย และการเก็บ password ไว้ใน cookie

### ISSUE THREAD

**Issue by webdevxp** [goragod/kotchasan#5]
class Password มี method ที่ใช้เข้ารหัส และถอดรหัส password (หรือข้อมูลอื่นๆ) ที่ใช้ algorithm แบบง่ายๆ
https://github.com/goragod/kotchasan/blob/master/Kotchasan/Password.php
และมีการเก็บรหัสผ่านที่เข้ารหัสไว้แล้วใน cookie
https://github.com/goragod/kotchasan/blob/master/Kotchasan/Login.php
ซึ่ง best practice ที่ทั่วโลกเขาปฏิบัติกันในปัจจุบันนั้น ไม่ควรเก็บ password ที่สามารถถอดรหัสได้ ควรเก็บเป็น hash ของมัน เพราะหากว่าระบบไหนเก็บ password ที่ถอดรหัสได้ มันหมายความว่าผู้ดูแลระบบนั้นสามารถรู้รหัสผ่านของผู้ใช้ได้ และจากสถิติแล้วคนทั่วไปมักจะใช้รหัสผ่านซ้ำๆ กันกับหลายๆ เว็บ ดังนั้นผมเลยคิดว่าการที่เฟรมเวิร์คสนับสนุนให้ผู้ใช้เขียนโปรแกรมเก็บรหัสผ่านที่ถอดรหัสออกมาเป็น plain text ได้เนี่ย นอกจากจะไม่ปลอดภัยแล้ว ยังอาจจะเรียกได้ว่าเป็นการละเมิด privacy ของผู้ใช้อีกด้วยครับ
และผมไม่เห็นเฟรมเวิร์ค/CMS ไหนในปัจจุบันเขาเก็บรหัสผ่านกันตรงๆ แล้วนะครับ

แต่ถ้ายังจะยืนยันว่าจะใช้วิธีนี้ อย่างน้อยแนะนำให้ใช้ฟังก์ชั่นเข้ารหัส/ถอดรหัสที่ PHP มีมาให้จะดีกว่า เช่น ฟังก์ชั่นใน extension OpenSSL
ส่วนเรื่องเก็บ password ไว้ใน cookie ซึ่งผมเข้าใจว่าคุณกรกฏใช้เพื่อทำระบบ remember me แต่การทำระบบนี้มันไม่จำเป็นที่จะต้องเก็บรหัสผ่านเลยครับ ใช้แนวคิดประเภทเก็บ token แทนรหัสผ่านก็ได้ ไม่ได้ยากอะไรเลยครับ จะเก็บรหัสผ่านให้มันมีช่องโหว่ทำไม

**Comment by goragod** [comment]
ที่ผมไม่ได้ตอบ เพราะเป็นคำถามที่ผมตอบไปหลายครั้งแล้วครับ ซึ่งถ้าผู้ถามได้ค้นคว้ามาบ้างจะทราบว่าจุดประสงค์ของคลาสคืออะไร

ผมทราบในความปราถนาดีที่มี แต่ผมก็มีแนวทางของผม ซึ่งไม่จำเป็นต้องตรงกับใครนะครับ ผมเลือกเกณฑ์ความปลอดภัยในแบบที่ผมยอมรับได้ ซึ่งผมมองว่ามันปลอดภัยเพียงพอ

สำหรับคนที่เห็นต่าง ถ้าคุณคิดว่าคลาส Password ไม่ปลอดภัยเพียงพอ คุณไม่จำเป็นต้องใช้มันก็ได้ ระบบไม่ได้บังคับให้คุณต้องใช้ คุณสามารถเลือกคลาสจากที่อื่นมาใช้งานประกอบ หรือแม้แต่ ใช้คำสั่งของ PHP ที่มีอยู่แล้วมาทดแทนได้ โดยไม่จำเป็นต้องแก้ไขคลาสผมเลย เพียงแค่มีความรู้เพียงพอเท่านั้น (นอกจากจะเขียนคลาสใช้เองไม่เป็น)

ส่วนเรื่อง Login ผมยังหาวิธีที่ดีกว่าไม่ได้ผมจึงยังใช้มันอยู่ ผมเองก็รอใครสักคนที่มีความจริงใจ จะช่วยผม ไม่ใช่คนที่จะมาบอกว่าแบบโน้นไม่ดีแบบนั่นไม่ใช้ best particle แล้วก้ไป เพราะมันไม่ช่วยอะไรให้ดีขึ้น ซึ่งร้อยคนก็ดูออกครับว่าเจตนาเพื่ออะไร

ผมยังยืนยันกฏการ Contribute ของผมนะครับ และผมจะไม่ตอบคำถาม ที่ซ้ำซากแบบนี้อีก ถ้าอยากแสดงความเห็นกรุณาทำตามกฏ และผมจะลบทุกความเห็นที่ผมเห็นสมควรว่าถูกลบ

**Comment by pjamenaja** [comment]
คือ ประเด็นคือ แบบนี้ครับ คนที่เราเอาซอฟต์แวร์ไปลงติดตั้งให้เค้า เค้าได้ทราบจุดโหว่ตรงนี้มั้ยครับ ตรงนี้เราได้มีการรับมืออย่างไรบ้างครับ ลูกค้าที่เอาโค้ดตรงนี้ไปใช้แล้ว อาจจะเป็นหน่วยงานราชการ เอกชน หากเป็นหน่วยงานราชการ ในฐานนะคนที่เสียภาษีคนหนึ่ง ผมก็อาจจะต้องรายงานจุดโหว่นี้ให้กับบุคคลที่เกี่ยวข้องทราบต่อไปนะครับ

**Comment by goragod** [comment]
เก็บ password ที่ถอดรหัสได้ มันหมายความว่าผู้ดูแลระบบนั้นสามารถรู้รหัสผ่านของผู้ใช้ได้ **ข้อนี้ไม่จริงนะครับ เพราะ cookie อยู่ในเครื่องผุ้ใช้ เราไม่ทราบ cookie ก็ไม่มีทางได้รหัสผ่านมา**

**Comment by pjamenaja** [comment]
จะลบความเห็นผมทำไมอะครับ มันไม่ได้มีอะไรที่เป็นการหยาบคายหรือโจมตีให้คุณกรกฎเสียหายเลยนะครับ เราควรที่จะให้ผู้ที่เข้ามาอ่านทีหลังเห็นบทสนทนาว่ามันมี issue อะไรบ้างนะครับ เพื่อที่ผู้เข้ามาทีหลังจะได้เข้าใจว่ามีอะไรที่ต้องคำนึงถึงบ้าง ก่อนที่จะเอา framework คชสาร ไปใช้นะครับ

**Comment by pjamenaja** [comment]
คือ จะเห็นด้วยหรือไม่เห็นด้วย แก้หรือไม่แก้ อันนี้ก็ไม่เป็นไรครับ แต่ทำไมเราไม่เปิดโอกาสให้คนที่มาทีหลังได้อ่านบทสนทนาแล้วให้เค้าตัดสินใจ หรือว่าระลึกไว้ หรือเข้าใจในตัว issue ล่ะครับ

**Comment by goragod** [comment]
ผมลบเฉพาะอันที่พยายามก่อกวนนะครับ เพราะถ้าผมลบหมด อันนี้คงไม่อยู่แล้ว
ย้ำอีกครั้ง กรุณาทำตามกฏนะครับ

**Comment by webdevxp** [comment]
อันไหนพยายามก่อกวนครับ อย่าลืมนะครับ คุณลบได้ก็จริง แต่มันก็มีหลักฐานเป็นเมล์ส่งมานะครับว่าใคร comment อะไร

**Comment by goragod** [comment]
ถ้าอยากให้คำพูดที่คุณพยายามสื่อสารมาทั้งหมด สำเร็จ แนะนำให้ไปเขียน แล้ว  commit มานะครับ จะเสียเวลาน้อยกว่ามาโต้เถียงกัน ถ้ามันดีจริง มีหรือที่ผมจะไม่ยอมรับ

หมายเหตุ ถ้าไม่มีอะไรใหม่ ผมลบทั้งหมดนะครับ มันรบกวนการทำงานของผม
